### ISSUE TITLE
FlowRouter SSR don't work properly

### ISSUE THREAD

**Issue by ahxar** [mantrajs/kickstart-mantrajs-webpack#15]
I already implementing FlowRouter SSR. but have one problem.
when defining `FlowRouter.route` inside `function (injectDeps)`. SSR won't working, but after defining `FlowRouter.route` outside `function (injectDeps)` it will work.

**Comment by ahxar** [comment]
Hey i got solution for this:
1. `import './client/main'` in `server.js`, so all client stuff loads in server too.
2. Only load `methodStubs` in client using `Meteor.isClient`
3. Load all assets (if using webpack loader) inside `Meteor.isClient` block

SSR in MantraJS + Webpack is working now :)

**Comment by ansonla3** [comment]
hi how can you make ssr works ? could you share the demo in github ? I didn't work as expected . it did not render the html elements.
Thanks very much

**Comment by ahxar** [comment]
hi @ansonla3 . Just follow my solution above and make sure you're import `kadira:flow-router-ssr` not `kadira:flow-router`
