### ISSUE TITLE
METEOR@1.2.1?

### ISSUE THREAD

**Issue by fallenpeace** [mantrajs/kickstart-mantrajs-webpack#2]
Why, is this project using METEOR  1.2.1?
I thought mantra was supposed to be 1.3+ specific? 

https://kadirahq.github.io/mantra/#sec-ES2015-Syntax-and-ES2015-Modules

**Comment by tomitrescak** [comment]
Nope. Mantra is only using 1.3 because it has "support" for es6 modules. This project uses webpack with full support of module and code splitting.

**Comment by fallenpeace** [comment]
ah okay that makes sense! Currently debating if I should use webpack, have you seen any examples of 1.3 webpack?

**Comment by tomitrescak** [comment]
This project is compatible with both. Just update your project to 1.3 and you are good to go. 1.3 is still in beta though, that is why 1.2.1 is used.

**Comment by tomitrescak** [comment]
I'll close this for now, ok? Reopen if necessary.
