### ISSUE TITLE
Update to Meteor 1.3 / webpack:webpack 1.0.12

### ISSUE THREAD

**Issue by ItsBenCodes** [mantrajs/kickstart-mantrajs-webpack#9]
Meteor 1.3 is out! I've updated webpack so I wanted to let you know so you can upgrade the packages :)

**Comment by yogiben** [comment]
It would be great to get a comment from @arunoda whether Mantra is looking to adopt webpack officially or whether it will always be a choice: webpack vs. no-webpack

**Comment by arunoda** [comment]
@yogiben Mantra is a guideline for app architecture. So we are pretty okay with whether it's webpack or no-webpack. I hope both have pros and cons.

So, it's up to you to decide :)

**Comment by genyded** [comment]
I know this is a few weeks old, but one thing to consider - and the reason most use webpack with Meteor is for HMR and code splitting. But HMR requires React classes and Mantra leans towards functional components with classes only for container components. While either seems to work OK, to get webpacks HMR, you MUST use React classes even for non-container components. It may be worth pointing this out somewhere.

**Comment by tomitrescak** [comment]
@genyded it is written in the read me with big phat letters ;)

> Mantra prefers to use stateless (bare) react components. These components do not support HMR. If you want to use HRM, you need to use standard React components:

**Comment by genyded** [comment]
Guess I need to learn how to read ;-)

**Comment by tomitrescak** [comment]
Nah, happens all the time to me ;) I'll close this as I have also accpeted the PR. Thanks!

**Comment by yogiben** [comment]
@tomitrescak I had a discussion with my team today about stateless components

Where can I find the arguments for using them?

**Comment by tomitrescak** [comment]
I would not write it better than this: https://medium.com/@joshblack/stateless-components-in-react-0-14-f9798f8b992d#.6w2i4ah03
- react agnostic
- pressuring for better component design
- cleaner
- nicer code
- better performance
- easier unit tests (questionable)
